package com.scm.all.pfunc.Nonvirtual;

interface XEleEventCallBack_Nonvirtual {
    boolean OnAdjustLayoutEnd(int hEle, long nFlags,int nAdjustNo);
    boolean OnBtnClick(int hEle);
    boolean OnButtonCheck(int hEle,boolean bCheck);
    boolean OnChar(int hEle, int wParam,int lParam);
    boolean OnComboBoxExitList(int hEle);;
    boolean OnComboBoxSelect(int hEle, int iItem);
    boolean OnComboBoxSelectEnd(int hEle, int iItem);
    boolean OnDateTimeChange(int hEle);
    boolean OnDateTimeExitMonthCal(int hEle,int hMonthCalWnd,int hMonthCal);
    boolean OnDateTimePopupMonthCal(int hEle,int hMonthCalWnd,int hMonthCal);
    boolean OnDestroy(int hEle);
    boolean OnDestroyeEnd(int hEle);
    boolean OnDropFiles(int hEle, String filesInfo);
    boolean OnEditChanged(int hEle);
    boolean OnEditColorChange(int hEle,long color);
    boolean OnEditDrawRow(int hEle,long hDraw, int iRow);
    boolean OnEditEnterGetTabAlign(int hEle);
    boolean OnEditPosChanged(int hEle,int iPos);
    boolean OnEditorBreakpointChanged(int hEle,int iRow, int nChangeRows);
    boolean OnEditSet(int hEle);
    boolean OnEditStyleChanged(int hEle,int iStyle);
    boolean OnEditSwapRow(int hEle,int iRow,int bArrowUp);
    boolean OnEditorAutoMatchSelect(int hEle,int iRow, int nRows);
    boolean OnEditorFormatCodeTest(int hEle,int iRow, int iCol);
    boolean OnEditChangeRows(int hEle,int iRow, int nRows);
    boolean OnEditorRemoveBreakpoint(int hEle,int iRow);
    boolean OnEditorSetBreakpoint(int hEle,int iRow, boolean bCheck);
    boolean OnEventProc(int hEle,long nEvent, int wParam, int lParam);
    boolean OnKeyDown(int hEle, int wParam, int lParam);
    boolean OnKeyUp(int hEle, int wParam, int lParam);
    boolean OnKillCapture(int hEle);
    boolean OnKillFocus(int hEle);
    boolean OnLButtonDBClick(int hEle, long flags, int x, int y);
    boolean OnLButtonDown(int hEle, long flags, int x, int y);
    boolean OnLButtonUp(int hEle, long flags, int x, int y);
    boolean OnListDrawItem(int hEle,long hDraw ,int index,int iSubItem,int nState,int hLayout,int hTemp);
    boolean OnListHeaderTemplateCreate(int hEle,int index,boolean bSort,int nSortType,int iColumnAdapter,int nState,int hLayout,int hTemp);
    boolean OnListHeaderClick(int hEle,int iItem);
    boolean OnListHeaderDrawItem(int hEle,long hDraw, int index,boolean bSort,int nSortType,int iColumnAdapter,int nState,int hLayout,int hTemp);
    boolean OnListHeaderTemplateCreateEnd(int hEle,int index,boolean bSort,int nSortType,int iColumnAdapter,int nState,int hLayout,int hTemp);
    boolean OnListHeaderTemplateDestroy(int hEle,int index,boolean bSort,int nSortType,int iColumnAdapter,int nState,int hLayout,int hTemp);
    boolean OnListHeaderItemWidthChange(int hEle,int iItem,int nWidth);
    boolean OnListSelect(int hEle,int iItem);
    boolean OnListTemplateCreate(int hEle,int index,int iSubItem,int nState,int hLayout,int hTemp,int nFlag);
    boolean OnListTemplateCreateEnd(int hEle,int index,int iSubItem,int nState,int hLayout,int hTemp,int nFlag);
    boolean OnListTemplateDestroy(int hEle,int index,int iSubItem,int nState,int hLayout,int hTemp,int nFlag);
    boolean OnListBoxDrawItem(int hEle,long hDraw,int index,int nHeight,int nSelHeight,int nState,int hLayout,int hTemp);
    boolean OnListBoxSelect(int hEle,int iItem);
    boolean OnListBoxTemplateCreate(int hEle,int index,int nHeight,int nSelHeight,int nState,int hLayout,int hTemp,int nFlag);
    boolean OnListBoxTemplateCreateEnd(int hEle,int index,int nHeight,int nSelHeight,int nState,int hLayout,int hTemp,int nFlag);
    boolean OnListBoxTemplateDestroy(int hEle,int index,int nHeight,int nSelHeight,int nState,int hLayout,int hTemp,int nFlag);
    boolean OnListViewDrawItem(int hEle,long hDraw,int iGroup,int item,int nState,int hLayout,int hTemp);
    boolean OnListViewExpand(int hEle,int iGroup,boolean bExpand);
    boolean OnListViewSelect(int hEle,int iGroup,int iItem);
    boolean OnListViewTemplateCreate(int hEle,int nFlag,int iGroup,int item,int nState,int hLayout,int hTemp);
    boolean OnListViewTemplateCreateEnd(int hEle,int nFlag,int iGroup,int item,int nState,int hLayout,int hTemp);
    boolean OnListViewTemplateDestroy(int hEle,int nFlag,int iGroup,int item,int nState,int hLayout,int hTemp);
    boolean OnMenuDrawBackground(int hEle,long hDraw,int hMenu,int hWindow,int nParentID);
    boolean OnMenuDrawItem(int hEle,long hDraw,int hMenu,int hWindow ,int nID,int nState,int hIcon,String pText);
    boolean OnMenuExit(int hEle);
    boolean OnMenuPopup(int hEle,int hMenu);
    boolean OnMenuPopupWnd(int hEle,int hMenu,int hWindow,int nParentID);
    boolean OnMenuSelect(int hEle,int nItem);
    boolean OnCalendarChange(int hEle);
    boolean OnMouseHover(int hEle,long nFlags, int x,int y);
    boolean OnMouseLeave(int hEle,int hEleStay);
    boolean OnMouseMove(int hEle,long nFlags, int x,int y);
    boolean OnMouseStay(int hEle);
    boolean OnMouseWheel(int hEle,long nFlags, int x,int y);
    boolean OnDraw(int hEle,long hDraw);
    boolean OnPaintEnd(int hEle,long hDraw);
    boolean OnDrawScrollView(int hEle,long hDraw);
    boolean OnPGridItemAdjustCoordinate(int hEle,int nType,int nID,int nDepth,int nNameColWidth,int bExpand,int bShow);
    boolean OnPGridItemDestroy(int hEle,int nItemID);
    boolean OnPGridItemExpand(int hEle,int nItemID, boolean bExpand);
    boolean OnPGridItemSelect(int hEle,int nItemID);
    boolean OnPGridItemSet(int hEle,int nItemID);
    boolean OnPGridValueChange(int hEle,int nItemID);
    boolean OnProgressBarChange(int hEle,int pos);
    boolean OnRButtonDown(int hEle,long nFlags, int x,int y);
    boolean OnRButtonUp(int hEle,long nFlags, int x,int y);
    boolean OnSBarScroll(int hEle,int pos);
    boolean OnScrollViewScrollH(int hEle,int pos);
    boolean OnScrollViewScrollV(int hEle,int pos);
    boolean OnSetCapture(int hEle);
    boolean OnSetCursor(int hEle,int wParam,int lParam);
    boolean OnSetFocus(int hEle);
    boolean OnSetFont(int hEle);
    boolean OnShow(int hEle,boolean bShow);
    boolean OnSize(int hEle,long nFlags, int nAdjustNo);
    boolean OnSliderBarChange(int hEle,int pos);
    boolean OnTabBarDelete(int hEle,int iItem);
    boolean OnTabBarSelect(int hEle,int iItem);
    boolean OnTooltipPopup(int hEle,int hWindowTooltip, String pText);
    boolean OnTreeDragItem(int hEle,int nDragItem,int nDestItem,int nType);
    boolean OnTreeDragItemIng(int hEle,int nDragItem,int nDestItem,int nType);
    boolean OnTreeDrawItem(int hEle,long hDraw,int nID,int nDepth,int nHeight,int nSelHeight,boolean bExpand,int nState,int hLayout,int hTemp);
    boolean OnTreeExpand(int hEle,int id,int bExpand);
    boolean OnTreeSelect(int hEle,int nItemID);
    boolean OnTreeTemplateCreate(int hEle,int nFlag,int nID,int nDepth,int nHeight,int nSelHeight,boolean bExpand,int nState,int hLayout,int hTemp);
    boolean OnTreeTemplateCreateEnd(int hEle,int nFlag,int nID,int nDepth,int nHeight,int nSelHeight,boolean bExpand,int nState,int hLayout,int hTemp);
    boolean OnTreeTemplateDestroy(int hEle,int nFlag,int nID,int nDepth,int nHeight,int nSelHeight,boolean bExpand,int nState,int hLayout,int hTemp);
    boolean OnEleXCTimer(int hEle,long nTimerID);
    boolean OnAutoEvent(int hEle,long len,long typeCode,byte[] data);
    boolean OnComboBoxPopupList(int hEle,int hWindow,int hListBox);
}
