package com.scm.all.pfunc;

public class BreakpointCallBackX64 {
    public void callback(
        long ExceptionAddress,
        long P1Home,
        long P2Home,
        long P3Home,
        long P4Home,
        long P5Home,
        long P6Home,
        long ContextFlags,
        long MxCsr,
        long SegCs,
        long SegDs,
        long SegEs,
        long SegFs,
        long SegGs,
        long SegSs,
        long EFlags,
        long Dr0,
        long Dr1,
        long Dr2,
        long Dr3,
        long Dr6,
        long Dr7,
        long Rax,
        long Rcx,
        long Rdx,
        long Rbx,
        long Rsp,
        long Rbp,
        long Rsi,
        long Rdi,
        long R8,
        long R9,
        long R10,
        long R11,
        long R12,
        long R13,
        long R14,
        long R15,
        long Rip,
        long VectorControl,
        long DebugControl,
        long LastBranchToRip,
        long LastBranchFromRip,
        long LastExceptionToRip,
        long LastExceptionFromRip) {
        return;
    }
}
