package com.scm.all.pfunc;

/**
 * 报表设计回调
 */
public class CGRDesignerEventHandler {
    // ========================================
    // Context Menu Events
    // ========================================

    /**
     * LayoutPanelContextMenu - Triggered when right-clicking on the layout panel
     */
    public void onLayoutPanelContextMenu() {
        return;
    }

    /**
     * InspectorContextMenu - Triggered when right-clicking on the inspector panel
     */
    public void onInspectorContextMenu() {
        return;
    }

    /**
     * ExplorerContextMenu - Triggered when right-clicking on the explorer panel
     */
    public void onExplorerContextMenu() {
        return;
    }

    // ========================================
    // Change Events
    // ========================================

    /**
     * InspectorChange - Triggered when the inspector property changes
     */
    public void onInspectorChange() {
        return;
    }

    /**
     * DataChange - Triggered when the report data changes
     */
    public void onDataChange() {
        return;
    }

    // ========================================
    // File Operations
    // ========================================

    /**
     * OpenReport - Triggered when a report is opened in the designer
     */
    public void onOpenReport() {
        return;
    }

    /**
     * SaveReport - Triggered when a report is saved from the designer
     */
    public void onSaveReport() {
        return;
    }

    // ========================================
    // Action Events
    // ========================================

    /**
     * BeforeDoAction - Triggered before each task action is executed
     * Parameters:
     *   actionEnum - Action enumeration value:
     *     101: Undo
     *     102: Redo
     *     103: Cut
     *     104: Paste
     *     105: Copy
     *     106: Delete
     *     107: SelectAll
     *     201: AutoAdjustTextBoxSize
     *     202: AutoGenerateColumns
     *     203: AutoGenerateFields
     *     204: MoveSectionUp
     *     205: MoveSectionDown
     *     206: AutoGenerateParameters
     *     207: AutoGenerateDataSetFields
     *     301: OpenPageSetupDialog
     *     302: OpenDataBindingDialog
     *     303: OpenParameterCollectionDialog
     *     304: OpenGroupCollectionDialog
     *     305: OpenColumnCollectionDialog
     *     306: OpenFieldCollectionDialog
     *     307: OpenColumnArrangeDialog
     *     308: BrowseScript
     *     309: ExitSubReportDesign
     *     310: OpenParameterQueryDialog
     *     311: OpenDataSetSetupDialog
     *     351-370: Free Table operations
     *     401-409: Add report elements
     *     501-520: Alignment operations
     *     600-627: Font and text alignment
     * Return value: 0 to allow action, non-zero to cancel action
     * @param actionEnum Action enumeration value
     * @return 0 to allow action, non-zero to cancel action
     */
    public int onBeforeDoAction(int actionEnum) {
        return 0;
    }

    /**
     * RequestData - Triggered when the report designer requests data
     * Parameters:
     *   pReport - Report object pointer (can be used to get IGridppReport interface)
     * @param pReport Report object pointer
     */
    public void onRequestData(int pReport) {
        return;
    }
}
